version: 0.2

env:
  shell: bash
  git-credential-helper: no

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing necessary components...
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt install terraform
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`