version: 0.2

env:
  shell: bash
  git-credential-helper: no
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
    TF_IN_AUTOMATION: "true"

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14
    commands:
      - echo preparing agent...
      - apt install curl -y
      - echo installing terraform...
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt install terraform -y
      - echo installing snyk...
      - npm install -g snyk
  pre_build:
    commands:
      - |
        terraform init \
          -backend-config="bucket=${TMPLTZ_TFSTATE_S3}" \
          -backend-config="key=codebuild/tfstate" \
          -backend-config="dynamodb_table=${TMPLTZ_TFLOCK_DYNAMODB}" \
          -input=false \
          -no-color
      - |
        terraform plan \
          -out="tf-plan-json" \
          -var "domain=templatize.app" \
          -var "environment=prod" \
          -input=false \
          -no-color
      - snyk iac test ./tf-plan.json --experimental
  build:
    commands:
      - terraform apply -auto-approve -compact-warnings -no-color tf-plan.json
  post_build:
    commands:
      - echo Build completed on `date`